language: ruby
sudo: false
before_install:
  # For testing purposes:
  - git config --local user.name "Samuel Williams"
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-2
env: COVERAGE=true
